### ISSUE TITLE
libnvToolsExt.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yohannes-taye** [darglein/ADOP#39]
Even after adding the directory path to the  LD_LIBRARY_PATH the error still persists.

**Comment by darglein** [comment]
Can you please post `echo $LD_LIBRARY_PATH` here

**Comment by yohannes-taye** [comment]
This is the output I get. 
`~/anaconda3/envs/adop/lib:`

**Comment by yohannes-taye** [comment]
I was able to resolve the issue by also including the lib64 directory inside the cuda installation folder. 
In my case it was under `/usr/local/cuda/lib64`

**Comment by albertz** [comment]
I used `patchelf ...your_lib.so --add-rpath ...`. Via `ldd ...your_lib.so`, I was checking whether it still failed to resolved some library. I added further paths until it found all. All the paths somewhere in `...lib/python3.12/site-packages/nvidia/...`.

(This is for another unrelated package, but I got the same error/problem there, and this issue here was one of the first Google hits, so I thought having this here might be helpful.)
